service: gestion-empleados-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: lbriceno-personal
  stage: ${opt:stage}
  region: ${opt:region}

plugins:
  - serverless-offline

functions:
  getEmpleados:
    handler: infraestructure/handlers/empleados-handler.getEmpleados
    events:
      - http:
          path: empleados       # https://dominio.fulanito/{stage}/empleados
          method: get
  createEmpleado:
    handler: infraestructure/handlers/empleados-handler.createEmpleado
    events:
      - http:
          path: empleados       # https://dominio.fulanito/{stage}/empleados
          method: post
  updateEmpleado:
    handler: infraestructure/handlers/empleados-handler.updateEmpleado
    events:
      - http:
          path: empleados/{id}       # https://dominio.fulanito/{stage}/empleados/{id}
          method: put
  deleteEmpleado:
    handler: infraestructure/handlers/empleados-handler.deleteEmpleado
    events:
      - http:
          path: empleados/{id}       # https://dominio.fulanito/{stage}/empleados/{id}
          method: delete
  getDetailEmpleado:
    handler: infraestructure/handlers/empleados-handler.getDetailEmpleado
    events:
      - http:
          path: empleados/{id}       # https://dominio.fulanito/{stage}/empleados/{id}
          method: get