service: gestion-empleados-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: lbriceno-personal
  stage: ${opt:stage}
  region: ${opt:region}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello       # https://dominio.fulanito/{stage}/hello
          method: get